(function(z,r,u,f,v,G){function w(b){return!isNaN(parseFloat(b))&&isFinite(b)}function A(b){return(new RegExp(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i)).test(b)}function U(b){return(new RegExp(/^[0-9a-f]{32}$/i)).test(b)}function V(b,d,c){b=b||[];var a=this,f=Math.floor((new Date).getTime()/1E3);a._session={rtgsession_ts_creation_cookie:b[0],rtgsession_ttl:b[1],rtgsession_seq:b[2],rtgsession_id_prev:b[3],rtgsession_id:b[4],rtgsession_ts:b[5],rtgsession_hits:b[6]};a.setUpNewSession=
function(){a._session.rtgsession_id=d+":"+f;a._session.rtgsession_ts=f;a._session.rtgsession_hits=1};a.setUpNewSessionHeader=function(){a._session.rtgsession_ts_creation_cookie=f;a._session.rtgsession_ttl=c;a._session.rtgsession_seq=1;a._session.rtgsession_id_prev=""};a.getValue=function(){return a._session.rtgsession_ts_creation_cookie+"_"+a._session.rtgsession_ttl+"_"+a._session.rtgsession_seq+"_"+a._session.rtgsession_id_prev+"_"+a._session.rtgsession_id+"_"+a._session.rtgsession_ts+"_"+a._session.rtgsession_hits};
a.getEncodedValue=function(){return encodeURIComponent(a.getValue())};a.createNew=function(){a.setUpNewSessionHeader();a.setUpNewSession()};a.checkError=function(){function b(a,b){c.isValid=!1;c.msg+=c.msg?"|"+a:a}function d(a){if(a&&(a=a.split(":"),a.length&&2===a.length))return A(a[0])&&w(a[1])}var c={isValid:!0,msg:""};try{w(a._session.rtgsession_ts_creation_cookie)?a._session.rtgsession_ts_creation_cookie=parseFloat(a._session.rtgsession_ts_creation_cookie):b("rtgsession_ts_creation_cookie"),
w(a._session.rtgsession_ttl)?a._session.rtgsession_ttl=parseFloat(a._session.rtgsession_ttl):b("rtgsession_ttl"),w(a._session.rtgsession_seq)?a._session.rtgsession_seq=parseFloat(a._session.rtgsession_seq):b("rtgsession_seq"),a._session.rtgsession_id_prev&&!d(a._session.rtgsession_id_prev)?b("rtgsession_id_prev"):(a._session.rtgsession_id_prev_uid=a._session.rtgsession_id_prev.split(":")[0],a._session.rtgsession_id_prev_ts=parseFloat(a._session.rtgsession_id_prev.split(":")[1])),a._session.rtgsession_id&&
!d(a._session.rtgsession_id)?b("rtgsession_id"):(a._session.rtgsession_id_uid=a._session.rtgsession_id.split(":")[0],a._session.rtgsession_id_ts=parseFloat(a._session.rtgsession_id.split(":")[1])),w(a._session.rtgsession_ts)?a._session.rtgsession_ts=parseFloat(a._session.rtgsession_ts):b("rtgsession_ts"),f<parseFloat(a._session.rtgsession_ts)&&b("rtgsession_duration"),w(a._session.rtgsession_hits)||b("rtgsession_hits")}catch(qa){k(c.msg+"+checkError+function+failed&trossion="+a.getEncodedValue()+
"&timestamp="+a.timeStamp,17)}return c};a.updateWithNewSession=function(){a._session.rtgsession_seq=parseFloat(a._session.rtgsession_seq)+1;a._session.rtgsession_id_prev=a._session.rtgsession_id;a.setUpNewSession()};a.updateSession=function(){a._session.rtgsession_ts=f;a._session.rtgsession_hits=parseFloat(a._session.rtgsession_hits)+1};a.updateEv=function(b){b=b||{};b.rtgsession_ts_creation_cookie=a._session.rtgsession_ts_creation_cookie;b.rtgsession_ttl=a._session.rtgsession_ttl;b.rtgsession_seq=
a._session.rtgsession_seq;b.rtgsession_id_prev=a._session.rtgsession_id_prev;b.rtgsession_id_prev_uid=a._session.rtgsession_id_prev_uid;b.rtgsession_id_prev_ts=a._session.rtgsession_id_prev_ts;b.rtgsession_id=a._session.rtgsession_id;b.rtgsession_id_uid=a._session.rtgsession_id_uid;b.rtgsession_id_ts=a._session.rtgsession_id_ts;b.rtgsession_ts=a._session.rtgsession_ts;b.rtgsession_hits=a._session.rtgsession_hits;b.rtgsession_duration=a._session.rtgsession_duration;b.rtgsession_seq_duration=a._session.rtgsession_seq_duration;
return b};a.getSessionForTagContainer=function(){return[["rtgsession_ts_creation_cookie",[a._session.rtgsession_ts_creation_cookie]],["rtgsession_ttl",[a._session.rtgsession_ttl]],["rtgsession_seq",[a._session.rtgsession_seq]],["rtgsession_id_prev",[a._session.rtgsession_id_prev]],["rtgsession_id_prev_uid",[a._session.rtgsession_id_prev_uid]],["rtgsession_id_prev_ts",[a._session.rtgsession_id_prev_ts]],["rtgsession_id",[a._session.rtgsession_id]],["rtgsession_id_uid",[a._session.rtgsession_id_uid]],
["rtgsession_id_ts",[a._session.rtgsession_id_ts]],["rtgsession_ts",[a._session.rtgsession_ts]],["rtgsession_hits",[a._session.rtgsession_hits]],["rtgsession_duration",[a._session.rtgsession_duration]],["rtgsession_seq_duration",[a._session.rtgsession_seq_duration]]]};(function(a){if(7>b.length)a.createNew();else{var d=a.checkError();d.isValid?f-parseFloat(a._session.rtgsession_ts)>c?a.updateWithNewSession():a.updateSession():(k(d.msg+"&trossion="+a.getEncodedValue()+"&timestamp="+a.timeStamp,17),
a.createNew())}a._session.rtgsession_id_ts&&a._session.rtgsession_ts&&(a._session.rtgsession_duration=a._session.rtgsession_ts-parseFloat(a._session.rtgsession_id_ts));a._session.rtgsession_id_ts&&a._session.rtgsession_id_prev_ts&&(a._session.rtgsession_seq_duration=a._session.rtgsession_ts-a._session.rtgsession_id_prev_ts)})(a);return a}function W(b,d){function c(){return[{id:"default",version:1,ttl:30,events:[{coef:-.1071305787347127},{coef:.216131896556964,cond:"rtgsession_seq"},{coef:1.2656065071142095E-4,
cond:"rtgsession_duration"},{coef:.07467899685829335,cond:"rtgsession_hits"}]}]}function a(a){try{return c().map(function(b){return m(b,a)})}catch(p){return k(p+"createNewScore: return score empty",20),c()}}function q(a,b){try{var d=parseFloat(a.value),c=parseFloat(a.lower_bound_value),f=parseFloat(a.upper_bound_value),p=parseFloat(b[a.key]);switch(a.operator){case "BETWEEN":return p>c&&p<f;case "==":return b[a.key]===a.value;case "<=":return p<=d;case ">=":return p>=d;case ">":return p>d;case "<":return p<
d;case "AND":return a.valueA&&a.valueB;case "OR":return a.valueA||a.valueB;case "IS NOT NULL":return b.hasOwnProperty(a.key)&&""!==b[a.key]&&void 0!==b[a.key];case "NOT":return!a.value;case "REGEXP":return(new RegExp(a.value,"giu")).test(b[a.key]);default:k(e+error.msg+"+operator not supported for visitor scoring",20)}}catch(S){k(S+"evaluateExpression",20)}}function g(a){try{var b=[];if("string"===typeof a&&0<a.length)for(var d=a.split(" ");d&&0<d.length;){var c=d.shift();if('"'===c[0]){if('"'!==
c[c.length-1])for(;;){var f=d.shift();if(void 0===f){c=void 0;break}c=c+" "+f;if('"'===f[f.length-1])break}void 0!==c&&(c=c.substring(1,c.length-1))}"IS"==c&&"NULL"===d[0]&&(c=c+" "+d.shift());"IS"==c&&"NOT"===d[0]&&"NULL"===d[1]&&(c=c+" "+d.shift()+" "+d.shift());void 0!==c&&b.push(c)}return b}catch(la){k(la+"lexer",20)}return[]}function l(a,b){var c=[];try{g(a).forEach(function(a){var d={operator:a};switch(a){case "BETWEEN":d.upper_bound_value=c.pop();d.lower_bound_value=c.pop();d.key=c.pop();a=
q(d,b);break;case "==":case "<=":case ">=":case ">":case "<":case "REGEXP":d.value=c.pop();d.key=c.pop();a=q(d,b);break;case "AND":case "OR":d.valueB=c.pop();d.valueA=c.pop();a=q(d,b);break;case "NOT":d.value=c.pop();a=q(d,b);break;case "IS NOT NULL":d.key=c.pop();a=q(d,b);break;case "!=":d.value=c.pop();d.key=c.pop();a=l(d.key+" "+d.value+" == NOT",b);break;case "IS NULL":d.key=c.pop(),a=l(d.key+" IS NOT NULL NOT",b)}c.push(a)})}catch(R){k(R+"processReversePolishNotation",20)}return c.pop()}function m(a,
b){function d(a,b){return function(d,c){try{var f=0,p=l(c.cond,b);if(void 0!==p)if("boolean"===typeof p){if(void 0===c.incr||a)c.incr=0;p&&(c.incr+=1);f=c.coef*c.incr}else f=c.coef*parseFloat(b[p])||0;else f=c.coef||0;return d+f}catch(H){return k(H+"setScore: scoreReducer: no score increment",20),d}}}try{var c=a.events.reduce(d(void 0===a.ts||b.rtgsession_ts-a.ts>86400*a.ttl,b),0);a.score=Math.floor(1E3/(1+Math.exp(-c)));a.ts=b.rtgsession_ts}catch(B){k(B+"setScore: could not compute score",20)}return a}
function n(a){var b={isValid:!0,msg:""};try{b=h.models.reduce(function(a,c){try{c.events.forEach(function(a){if(""===a.coef||void 0===a.coef)b.isValid=!1,b.msg+=b.msg?"|coef":"coef"})}catch(B){k(B+b.msg+"+checkError+function+failed&engagement",20)}return a},b)}catch(M){k(M+b.msg+"+checkError+function+failed&engagement",20)}return b}var h=this;h.models=[];var r=function(a){try{var b=a.filter(function(a){return"default"!==a.id});if(0<b.length)return encodeURIComponent(JSON.stringify(b))}catch(M){k(M+
"stringifyModels",20)}return""},t=function(){return r(h.models)};(function(b,d){try{var f;a:{try{if(b&&0<b.length){f=JSON.parse(decodeURIComponent(b));break a}}catch(B){k(B+"parseModels",20)}f=[]}h.models=f;0===h.models.length&&(h.models=c());var g=n(h.models);g.isValid?h.models=h.models.map(function(a){return m(a,d)}):(k(g.msg+"init+function+failed+model+not+valid+&engagement=20"),h.models=a(d))}catch(B){k(B+"+init+function+failed&engagement",20),h.models=a(d)}})(b,d);h.lexer=g;h.evaluateExpression=
q;h.processReversePolishNotation=l;h.getScores=function(a){function b(a,b,c){return a+"&"+b}function c(a){return void 0!==a?"rtg"+a.id+"_score="+encodeURIComponent(a.score)+"&rtg"+a.id+"_version="+encodeURIComponent(a.version):""}try{if(0<h.models.length)return h.models.map(c).reduce(b);k("+getScores+function+empty+models&engagement",20)}catch(R){k(R+"getScore",20)}return""};h.getScoresForTagContainer=function(){try{if(0<h.models.length)return h.models.reduce(function(a,b){a.push(["rtg"+b.id+"_score",
[b.score]]);a.push(["rtg"+b.id+"_version",[b.version]]);return a},[])}catch(ka){k(ka+"getScoresForTagContainer",20)}return[]};h.getEncodedModels=t;h.updateEv=function(a){function b(a,b){a["rtg"+b.id+"_score"]=b.score;a["rtg"+b.id+"_version"]=b.version;return a}try{0<h.models.length&&(a=h.models.reduce(b,a))}catch(M){k(M+"+updateEv fail",20)}return a};h.writeNewModelsToCookie=function(a){try{for(var b=[],c=h.models.reduce(function(a,b){a[b.id]=b;return a},{}),d=0;d<a.length;d+=1){var g=a[d];if(void 0!==
c[g.id]){for(var q=0;q<g.events.length;q+=1)c[g.id].events[q].coef=g.events[q].coef;c[g.id].version=g.version;b.push(c[g.id])}else b.push(a[d])}h.models=b;C("__trossion",f._session.getValue()+"_"+t(),395)}catch(S){k(S+"+writeNewModelsToCookie fail",20)}};return h}function Y(b){try{var d=Array.prototype.slice.call(arguments,0);b=d.shift();switch(b){case "init":f.tagid||(f.tagid=d[0],Z());break;case "session_ttl":d[0]&&(f.session_ttl=d[0]);break;case "tag":y=[];var c=d[0],d=[],a;for(a in c)if(c.hasOwnProperty(a))if("rtg"===
a.substring(0,3))y.push(D(a,[c[a]])),d.push([a,[c[a]]]);else if("exclusion"===a)y.push("exclusion=1"),d.push([a,["1"]]);else if("m5e"===a||"sha256"===a||"email"===a)y.push(D(a,[c[a]])),d.push([a,[c[a]]]);aa(y,d,c)}}catch(q){k(q,14)}}function aa(b,d,c){try{d.push(["r1",[n]]);c.r1=n;d.push(["vruid",[v]]);c.vruid=v;if(null!==x&&""!==x){var a;try{a=encodeURIComponent(x)}catch(m){a=escape(x)}d.push(["u",[a]]);c.u=a}var q=f.etag+"_"+(f.version?f.version:"0");d.push(["v",[q]]);c.v=q;if(f.tcf_consent){var g=
I("__trossion").split("_"),l=g.splice(7);f._session=new V(g,f.uid,f.session_ttl);f._session.updateEv(c);d=d.concat(f._session.getSessionForTagContainer());f._en=new W(l.join("_"),c);f._en.updateEv(c);b.push("trossion="+f._session.getEncodedValue())}if(!f.tagid)throw"tagid is missing";f.tcf_consent&&(b.push(f._en.getScores()),d=d.concat(f._en.getScoresForTagContainer()));""!=f.tcf_consent_string&&b.push("gdpr_consent="+f.tcf_consent_string);ba(b);f.tcf_consent&&C("__trossion",f._session.getValue()+
"_"+f._en.getEncodedModels(),395);f.segq.queue?f.segq.tag?f.segq.tag.apply(f.segq,c):f.segq.queue.push(c):f.segq.push.apply(f.segq,d)}catch(m){k(m,3)}}function ca(){if(!f.unqueue_called){try{if(f.queue)for(;f.queue.length;){var b=f.queue.shift();Y.apply(this,b)}else y=Array.prototype.splice.call(f,0),f.push()}catch(d){k(d,7)}f.unqueue_called=!0}}function da(b){try{b.queue&&(b=b.queue);for(var d=0;d<b.length;d++)if(b[d]&&b[d][0]&&("tagid"===b[d][0]||"init"===b[d][0])&&""!==b[d][1]){var c=b[d][1].split("-");
if(2!=c.length)throw"Tagid is misstructured"+encodeURIComponent(b[d][1]);if(!c[1]||!U(c[1]))throw"Tag hash is invalid"+encodeURIComponent(c[1]);if(!c[0]||!w(c[0]))throw"Tagid is invalid"+encodeURIComponent(c[0]);if(0!==c[0].indexOf("6"))throw"Tagid identifier is not valid  "+encodeURIComponent(c[0]);return b[d][1]}throw"Tagid is missing";}catch(a){k(a,13)}}z._troqck=z._troqck||0;if(!z._troqck){var E,ea=!1,n="",x=u;u=x.hostname.split(".").reverse();f.etag=G;E=2<u.length&&3>=u[1].length&&2>=u[0].length?
"."+u[2]+"."+u[1]+"."+u[0]:"."+u[1]+"."+u[0];z!==top&&r.referrer&&""!==r.referrer&&(x=r.referrer);var D=function(b,d){for(var c="",a=0;a<d.length;a++)0<a&&(c+="|"),c+=d[a];try{c=b+"="+encodeURIComponent(c)}catch(q){c=b+"="+escape(c)}return c};f.urlize=D;var ma=function(b){for(var d="",c=0,a=b.length;c<a;c+=1)var f=b.charCodeAt(c).toString(2),g="00000000".slice(0,8-f.length),d=d+(g+f);return d},na=function(b){if("function"===typeof atob){b=b.replace(/_/g,"/").replace(/-/g,"+");try{return atob(b)}catch(d){throw Error("Unable to decode transparency and consent string");
}}if("function"===typeof Buffer)return Buffer.from(b,"base64").toString("binary");throw Error("Unable to detect base64 decoder");},N=function(b){return parseInt(b,2)||0},fa=function(b){return 100*N(b)},ga=function(b){var d="A".charCodeAt();b=b.match(/.{6}/g)||[];for(var c="",a=0,f=b.length;a<f;a+=1)var g=N(b[a])+d,c=c+String.fromCharCode(g);return c},F=function(b){return!!Number(b)},J=function(b){b=b.split("");for(var d={},c=0,a=b.length;c<a;c+=1)F(b[c])&&(d[c+1]=!0);return d},ha=function(b,d,c,a){var f=
function(){if(a.pubRestrictionEntry&&a.rangeEntry)for(var c in a.rangeEntry)Object.prototype.hasOwnProperty.call(a.rangeEntry,c)&&(a.pubRestrictionEntry[c]=(a.pubRestrictionEntry[c]||[]).concat(a.rangeEntry[c]));a.numPubRestrictions&&(--a.numPubRestrictions,b.push({key:"purposeId",size:6},{key:"restrictionType",size:2},{key:"numEntries",size:12}))},g=function(){a.numEntries?(--a.numEntries,b.push({key:"isRange",size:1,decoder:F},{key:"startVendorId",size:16})):f()},k=function(){return a.purposeId?
[{purpose:a.purposeId,isAllowed:0!==a.restrictionType,isConsentRequired:1===a.restrictionType,isLegitimateInterestRequired:2===a.restrictionType}]:!0};if("isRangeEncoding"===d.key)b.push(c?{key:"numEntries",size:12}:{key:"bitField",size:a.maxVendorId,decoder:J});else if("numEntries"===d.key)a.rangeEntry={},g();else if("isRange"===d.key)c&&b.push({key:"endVendorId",size:16});else if("startVendorId"===d.key)a.isRange||(a.rangeEntry[c]=k(),g());else if("endVendorId"===d.key){for(d=a.startVendorId;d<=
a.endVendorId;d+=1)a.rangeEntry[d]=k();g()}else"numCustomPurposes"===d.key?b.push({key:"customPurposeConsents",size:a.numCustomPurposes,decoder:J},{key:"customPurposeLegitimateInterests",size:a.numCustomPurposes,decoder:J}):"numPubRestrictions"===d.key&&(a.pubRestrictionEntry={},f())},P=0,ia=function(b,d){var c=d.slice(P,P+b.size);P+=b.size;return(b.decoder||N)(c)},I=function(b){var d,c,a,f=r.cookie.split(";");for(d=0;d<f.length;d++)if(c=f[d].substr(0,f[d].indexOf("=")),a=f[d].substr(f[d].indexOf("=")+
1),c=c.replace(/^\s+|\s+$/g,""),c===b)try{return decodeURIComponent(a)}catch(g){return unescape(a)}return""};f.getCookie=I;var C=function(b,d,c){var a=new Date;a.setDate(a.getDate()+c);var f=d;try{d=encodeURIComponent(d)}catch(X){d=escape(d)}var g=d;c=null===c?"":"; expires="+a.toUTCString();g=g+c+("; domain="+E+"; path=/");r.cookie=b+"="+g;try{var l=I(b);if(""===l||l!=f){var m=z.location.hostname;if(1===m.split(".").length)r.cookie=b+"="+d+c+"; path=/";else{var n=m.split(".");n.shift();var h="."+
n.join(".");r.cookie=b+"="+d+c+"; path=/; domain="+h;l=I(b);if(""===l||l!=f)r.cookie=b+"="+d+c+"; path=/; domain="+E}}}catch(X){k(X,1)}};f.setCookie=C;f.isNumeric=w;f.isValidRUID=A;f.isMD5Valid=U;f.Session=V;f.Engagement=W;var ba=function(b,d){try{if(null==f.tagid||""===f.tagid)throw"tagid is missing";var c="tagid="+f.tagid+"&";f.tcf_consent&&(c+="r1="+n+"&",c+="vruid="+v+"&");for(;0<b.length;)c+=b.shift()+"&";if(null!==x&&""!==x){c+="u=";try{c+=encodeURIComponent(x)}catch(a){c+=escape(x)}c+="&"}c+=
"v="+f.etag+"_";c+=(f.version?f.version:"0")+"&";c+="rnd="+Math.round(2E9*Math.random());c="https://"+(d||"mmtro.com")+"/p?"+c;(new Image(1,1)).src=c}catch(a){k(a,3)}};f.troPix=ba;f.push=function(){try{for(var b=0;b<arguments.length;b++)y.push(arguments[b])}catch(h){k(h,4)}for(var b=[],d=[],c=[],a={};0<y.length;)try{var q=y.shift(),g=q.shift();if(!g)throw"empty array in taggage";var g=g.toLowerCase(),l=q,m=!1;if("tagid"===g)f.tagid||(f.tagid=da([[g,l[0]]])),m=!0;else if("rtg"===g.substring(0,3)||
-1!==g.indexOf("_")){0===g.indexOf("_")&&(g=g.substring(1,g.length));var n=D(g,l);d.push(n);c.push([g,l]);a[g]=n.split("=")[1]}else"exclusion"===g?(d.push("exclusion=1"),c.push([g,["1"]]),a.exclusion="1"):"m5e"===g||"sha256"===g||"email"===g?(n=D(g,l),d.push(n),c.push([g,l]),a[g]=n.split("=")[1]):b.push(D(g,l))}catch(h){k(h,5)}0<b.length&&k("wrong params in taggage "+b.join("&"),12);try{0<d.length||m?aa(d,c,a):k("p is empty",16)}catch(h){k(h,6)}};f.callTro=Y;f.unqueue=ca;var K=function(b){var d=r.createElement("script");
d.type="text/javascript";d.async=!0;d.src=b;b=r.getElementsByTagName("script")[0];b.parentNode.insertBefore(d,b)};f.createScript=K;f.jarSyncMMTRO=function(b){if(f.tcf_consent)try{C("__troRUID",b,395),n=f.uid=b}catch(d){k(d,10)}};var k=function(b,d){b=b.message||b;b=encodeURIComponent(b.replace(/ /g,"_"));var c="https://err.mmtro.com/error?f=tro.js&u="+encodeURIComponent(z.location.href)+"&message="+b+"&try="+d+"&v="+f.etag+"_"+(f.version?f.version:"0");(new Image(1,1)).src=c},Z=function(){if(null!=
f.tagid&&""!=f.tagid&&f.tcf_consent){if("00000000-0000-0000-0000-000000000000"!==n)try{K("https://cdn.mmtro.com/seg/"+f.tagid.split("-")[0]+".js")}catch(b){k(b,8)}K("https://mmtro.com/trojs/"+f.tagid+"/"+n+"/"+v+"/exec.js")}};G=function(){var b="",d="",c=["euconsent-v2","eupubconsent-v2"],a;for(a in c)if(b=I(c[a]),""!=b)try{var f;if("string"!==typeof b)throw Error("Invalid transparency and consent string specified");for(var g=b.split("."),l=[],m=0,n=g.length;m<n;m+=1)l.push(ma(na(g[m])));var h=N(l[0].slice(0,
6));if(2!==h)throw Error("Unsupported transparency and consent string version “"+h+"”");f=l;for(var r,l=f,m=[{key:"purposeConsents",size:24,decoder:J},{key:"purposeLegitimateInterests",size:24,decoder:J}],t=[{key:"maxVendorId",size:16},{key:"isRangeEncoding",size:1,decoder:F}],u=[{key:"version",size:6},{key:"created",size:36,decoder:fa},{key:"lastUpdated",size:36,decoder:fa},{key:"cmpId",size:12},{key:"cmpVersion",size:12},{key:"consentScreen",size:6},{key:"consentLanguage",size:12,decoder:ga},{key:"vendorListVersion",
size:12},{key:"policyVersion",size:6},{key:"isServiceSpecified",size:1,decoder:F},{key:"useNonStandardStacks",size:1,decoder:F},{key:"specialFeatureOptins",size:12,decoder:J}].concat(m).concat({key:"purposeOneTreatment",size:1,decoder:F},{key:"publisherCountryCode",size:12,decoder:ga},{key:"vendorConsents",queue:[{key:"maxVendorId",size:16},{key:"isRangeEncoding",size:1,decoder:F}]},{key:"vendorLegitimateInterests",queue:t},{key:"publisherRestrictions",queue:[{key:"numPubRestrictions",size:12}]}),
p=[{size:3}],x=[].concat(p).concat(t),y=[].concat(p).concat(t),B=[].concat(p).concat(m).concat({key:"numCustomPurposes",size:6}),m=[{key:"core",queue:u}],t=1;t<l.length;t+=1){var v=N(l[t].slice(0,3));1===v?m.push({key:"disclosedVendors",queue:x}):2===v?m.push({key:"allowedVendors",queue:y}):3===v&&m.push({key:"publisherTC",queue:B})}r=m;l={};for(m=0;m<r.length;m+=1){for(var w=r[m],z,t=w,D=f[m],p={},C=0;C<t.queue.length;C+=1){var H=t.queue[C],A;var O=H,G=D;if(O.queue){for(var L={},E=0;E<O.queue.length;E+=
1){var Q=O.queue[E],K=ia(Q,G);Q.key&&(L[Q.key]=K);ha(O.queue,Q,K,L)}A=L.pubRestrictionEntry||L.rangeEntry||L.bitField||L}else A=ia(O,G);H.key&&(p[H.key]=A);ha(t.queue,H,A,p)}z=p.pubRestrictionEntry||p.rangeEntry||p.bitField||p;w.key&&(l[w.key]=z);P=0}d=l;break}catch(ra){k("tcf consent string not valid: "+encodeURIComponent(b),21)}return[b,d]};try{var y=[];f.segq=f.segq||[];if(null==v||""==v||!A(v))throw"vruid is invalid";f.tcf_consent=!0;f.tcf_consent_string="";var ja=G(),oa=ja[0],T=ja[1];if(""!=
T){var pa=T.core.vendorConsents[388]||!1;f.tcf_consent=(T.core.purposeConsents[1]||!1)&&pa;f.tcf_consent_string=oa}f.tcf_consent&&(n=I("__troRUID"),A(n)||(n&&k("ruid1 not valid: "+encodeURIComponent(n),18),ea=!0,n=v),f.uid=n);f.session_ttl=1800;f.tagid=da(f);ca();ea&&C("__troRUID",n,395);Z()}catch(b){k(b,11)}z._troqck=1}})
(window, document, location, _troq, "6190f7c6-e83c-446b-b203-631a634d411a", "3243c260857728e0bf78288a");